/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PacoteInterfaceVisual;

/**
 *
 * @author CaioFSX
 */
public class PaginaCriarConta extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceVisual
     */
    public PaginaCriarConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPedirSenha = new javax.swing.JPanel();
        InformeSeuNome = new javax.swing.JTextField();
        CampoInserirNome = new javax.swing.JTextField();
        BotaoAvancarCriarConta = new javax.swing.JButton();
        InformeSeuEmail = new javax.swing.JTextField();
        CampoInserirEmail = new javax.swing.JTextField();
        PainelLogoPedirSenha = new javax.swing.JPanel();
        TituloBancoJava = new javax.swing.JTextField();
        ImagemLogoJava = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        JPanelPedirSenha.setBackground(new java.awt.Color(255, 255, 255));

        InformeSeuNome.setEditable(false);
        InformeSeuNome.setBackground(new java.awt.Color(255, 255, 255));
        InformeSeuNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        InformeSeuNome.setText("Informe seu Nome:");
        InformeSeuNome.setBorder(null);
        InformeSeuNome.setFocusable(false);
        InformeSeuNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeSeuNomeActionPerformed(evt);
            }
        });

        CampoInserirNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoInserirNomeActionPerformed(evt);
            }
        });

        BotaoAvancarCriarConta.setBackground(new java.awt.Color(204, 0, 0));
        BotaoAvancarCriarConta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoAvancarCriarConta.setForeground(new java.awt.Color(255, 255, 255));
        BotaoAvancarCriarConta.setText("Avançar");
        BotaoAvancarCriarConta.setBorderPainted(false);
        BotaoAvancarCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAvancarCriarContaActionPerformed(evt);
            }
        });

        InformeSeuEmail.setEditable(false);
        InformeSeuEmail.setBackground(new java.awt.Color(255, 255, 255));
        InformeSeuEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        InformeSeuEmail.setText("Informe seu E-mail:");
        InformeSeuEmail.setBorder(null);
        InformeSeuEmail.setFocusable(false);
        InformeSeuEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeSeuEmailActionPerformed(evt);
            }
        });

        CampoInserirEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoInserirEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelPedirSenhaLayout = new javax.swing.GroupLayout(JPanelPedirSenha);
        JPanelPedirSenha.setLayout(JPanelPedirSenhaLayout);
        JPanelPedirSenhaLayout.setHorizontalGroup(
            JPanelPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPedirSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InformeSeuNome, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoInserirNome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InformeSeuEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoInserirEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(JPanelPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPedirSenhaLayout.createSequentialGroup()
                    .addContainerGap(127, Short.MAX_VALUE)
                    .addComponent(BotaoAvancarCriarConta)
                    .addGap(114, 114, 114)))
        );
        JPanelPedirSenhaLayout.setVerticalGroup(
            JPanelPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPedirSenhaLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(InformeSeuNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoInserirNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InformeSeuEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoInserirEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPedirSenhaLayout.createSequentialGroup()
                    .addContainerGap(356, Short.MAX_VALUE)
                    .addComponent(BotaoAvancarCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)))
        );

        PainelLogoPedirSenha.setBackground(new java.awt.Color(204, 0, 0));

        TituloBancoJava.setEditable(false);
        TituloBancoJava.setBackground(new java.awt.Color(204, 0, 0));
        TituloBancoJava.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TituloBancoJava.setForeground(new java.awt.Color(255, 255, 255));
        TituloBancoJava.setText("Banco JAVA");
        TituloBancoJava.setBorder(null);
        TituloBancoJava.setFocusable(false);
        TituloBancoJava.setSelectedTextColor(new java.awt.Color(242, 242, 242));
        TituloBancoJava.setSelectionColor(new java.awt.Color(242, 242, 242));
        TituloBancoJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloBancoJavaActionPerformed(evt);
            }
        });

        ImagemLogoJava.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProjects\\sistema-bancario\\src\\main\\resources\\images\\java-logo-black-and-white-1.png")); // NOI18N
        ImagemLogoJava.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PainelLogoPedirSenhaLayout = new javax.swing.GroupLayout(PainelLogoPedirSenha);
        PainelLogoPedirSenha.setLayout(PainelLogoPedirSenhaLayout);
        PainelLogoPedirSenhaLayout.setHorizontalGroup(
            PainelLogoPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLogoPedirSenhaLayout.createSequentialGroup()
                .addGroup(PainelLogoPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLogoPedirSenhaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(TituloBancoJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelLogoPedirSenhaLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(ImagemLogoJava)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        PainelLogoPedirSenhaLayout.setVerticalGroup(
            PainelLogoPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLogoPedirSenhaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TituloBancoJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(ImagemLogoJava, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PainelLogoPedirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPanelPedirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelLogoPedirSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelPedirSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TituloBancoJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloBancoJavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloBancoJavaActionPerformed

    private void InformeSeuNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeSeuNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InformeSeuNomeActionPerformed

    private void CampoInserirNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoInserirNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoInserirNomeActionPerformed

    private void BotaoAvancarCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAvancarCriarContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoAvancarCriarContaActionPerformed

    private void InformeSeuEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeSeuEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InformeSeuEmailActionPerformed

    private void CampoInserirEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoInserirEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoInserirEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PaginaCriarConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAvancarCriarConta;
    private javax.swing.JTextField CampoInserirEmail;
    private javax.swing.JTextField CampoInserirNome;
    private javax.swing.JLabel ImagemLogoJava;
    private javax.swing.JTextField InformeSeuEmail;
    private javax.swing.JTextField InformeSeuNome;
    private javax.swing.JPanel JPanelPedirSenha;
    private javax.swing.JPanel PainelLogoPedirSenha;
    private javax.swing.JTextField TituloBancoJava;
    // End of variables declaration//GEN-END:variables
}
