/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PacoteInterfaceVisual;

import PacoteInterfaceVisual.Usuario.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author CaioFSX
 */
public class PaginaConfirmarCodigoEmail extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceVisual
     */
    public PaginaConfirmarCodigoEmail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPedirSenha = new javax.swing.JPanel();
        DigitarCodigoTitulo = new javax.swing.JTextField();
        BotaoConfirmarCodigo = new javax.swing.JButton();
        CampoInserirCodigo = new javax.swing.JFormattedTextField();
        PainelLogoPedirSenha = new javax.swing.JPanel();
        TituloBancoJava = new javax.swing.JTextField();
        ImagemLogoJava = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        JPanelPedirSenha.setBackground(new java.awt.Color(255, 255, 255));

        DigitarCodigoTitulo.setEditable(false);
        DigitarCodigoTitulo.setBackground(new java.awt.Color(255, 255, 255));
        DigitarCodigoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DigitarCodigoTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DigitarCodigoTitulo.setText("Digite o código de 4 dígitos que enviamos para seu e-mail:");
        DigitarCodigoTitulo.setBorder(null);
        DigitarCodigoTitulo.setFocusable(false);
        DigitarCodigoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitarCodigoTituloActionPerformed(evt);
            }
        });

        BotaoConfirmarCodigo.setBackground(new java.awt.Color(204, 0, 0));
        BotaoConfirmarCodigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoConfirmarCodigo.setForeground(new java.awt.Color(255, 255, 255));
        BotaoConfirmarCodigo.setText("Confirmar");
        BotaoConfirmarCodigo.setBorderPainted(false);
        BotaoConfirmarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConfirmarCodigoActionPerformed(evt);
            }
        });

        try {
            CampoInserirCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout JPanelPedirSenhaLayout = new javax.swing.GroupLayout(JPanelPedirSenha);
        JPanelPedirSenha.setLayout(JPanelPedirSenhaLayout);
        JPanelPedirSenhaLayout.setHorizontalGroup(
            JPanelPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPedirSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DigitarCodigoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(JPanelPedirSenhaLayout.createSequentialGroup()
                        .addComponent(CampoInserirCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(JPanelPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPedirSenhaLayout.createSequentialGroup()
                    .addContainerGap(112, Short.MAX_VALUE)
                    .addComponent(BotaoConfirmarCodigo)
                    .addGap(114, 114, 114)))
        );
        JPanelPedirSenhaLayout.setVerticalGroup(
            JPanelPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPedirSenhaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DigitarCodigoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoInserirCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(JPanelPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPedirSenhaLayout.createSequentialGroup()
                    .addContainerGap(356, Short.MAX_VALUE)
                    .addComponent(BotaoConfirmarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)))
        );

        PainelLogoPedirSenha.setBackground(new java.awt.Color(204, 0, 0));

        TituloBancoJava.setEditable(false);
        TituloBancoJava.setBackground(new java.awt.Color(204, 0, 0));
        TituloBancoJava.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TituloBancoJava.setForeground(new java.awt.Color(255, 255, 255));
        TituloBancoJava.setText("Banco JAVA");
        TituloBancoJava.setBorder(null);
        TituloBancoJava.setFocusable(false);
        TituloBancoJava.setSelectedTextColor(new java.awt.Color(242, 242, 242));
        TituloBancoJava.setSelectionColor(new java.awt.Color(242, 242, 242));
        TituloBancoJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloBancoJavaActionPerformed(evt);
            }
        });

        ImagemLogoJava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/java-logo-black-and-white-1.png"))); // NOI18N
        ImagemLogoJava.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PainelLogoPedirSenhaLayout = new javax.swing.GroupLayout(PainelLogoPedirSenha);
        PainelLogoPedirSenha.setLayout(PainelLogoPedirSenhaLayout);
        PainelLogoPedirSenhaLayout.setHorizontalGroup(
            PainelLogoPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLogoPedirSenhaLayout.createSequentialGroup()
                .addGroup(PainelLogoPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLogoPedirSenhaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(TituloBancoJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelLogoPedirSenhaLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(ImagemLogoJava)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        PainelLogoPedirSenhaLayout.setVerticalGroup(
            PainelLogoPedirSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLogoPedirSenhaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TituloBancoJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(ImagemLogoJava, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PainelLogoPedirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPanelPedirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelLogoPedirSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelPedirSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TituloBancoJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloBancoJavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloBancoJavaActionPerformed

    private void DigitarCodigoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitarCodigoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DigitarCodigoTituloActionPerformed

    private void BotaoConfirmarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConfirmarCodigoActionPerformed
        // TODO add your handling code here:
        if(Integer.valueOf(CampoInserirCodigo.getText()) == Usuario.getCodigoRecuperacao()){
            this.dispose();
            JOptionPane.showMessageDialog(null, "Codigo Correto!", "BANCO JAVA", JOptionPane.INFORMATION_MESSAGE);
            PaginaRedefinirSenha p1 = new PaginaRedefinirSenha();
            p1.setVisible(true);
        } else{
            JOptionPane.showMessageDialog(null, "Codigo Incorreto, verifique seu e-mail!", "BANCO JAVA", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BotaoConfirmarCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaConfirmarCodigoEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaConfirmarCodigoEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaConfirmarCodigoEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaConfirmarCodigoEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PaginaConfirmarCodigoEmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoConfirmarCodigo;
    private javax.swing.JFormattedTextField CampoInserirCodigo;
    private javax.swing.JTextField DigitarCodigoTitulo;
    private javax.swing.JLabel ImagemLogoJava;
    private javax.swing.JPanel JPanelPedirSenha;
    private javax.swing.JPanel PainelLogoPedirSenha;
    private javax.swing.JTextField TituloBancoJava;
    // End of variables declaration//GEN-END:variables
}
