/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PacoteInterfaceVisual;

import PacoteInterfaceVisual.Usuario.Usuario;
import PacoteRegraDeNegocio.ValidarInformacoesUsuario;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author CaioFSX
 */
public class PaginaHome extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceVisual
     */
    public PaginaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelHOME = new javax.swing.JPanel();
        BotaoConsultarExtrato = new javax.swing.JButton();
        IconeLogo = new javax.swing.JLabel();
        NomeCliente = new javax.swing.JTextField();
        BotaoParcerias = new javax.swing.JButton();
        BotaoRecarregarCelular = new javax.swing.JButton();
        BotaoPagar = new javax.swing.JButton();
        BotaoAreaPIX = new javax.swing.JButton();
        BotaoConsultarSaldo = new javax.swing.JButton();
        PerguntasFrequentes = new javax.swing.JTextField();
        BotaoPerfilConfiguracoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        JPanelHOME.setBackground(new java.awt.Color(255, 255, 255));

        BotaoConsultarExtrato.setBackground(new java.awt.Color(204, 0, 0));
        BotaoConsultarExtrato.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoConsultarExtrato.setForeground(new java.awt.Color(255, 255, 255));
        BotaoConsultarExtrato.setText("ConsultarExtrato");
        BotaoConsultarExtrato.setBorderPainted(false);
        BotaoConsultarExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultarExtratoActionPerformed(evt);
            }
        });

        IconeLogo.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProjects\\sistema-bancario\\src\\main\\resources\\images\\logoCircular2.png")); // NOI18N
        IconeLogo.setText("jLabel1");

        NomeCliente.setEditable(false);
        NomeCliente.setBackground(new java.awt.Color(255, 255, 255));
        NomeCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NomeCliente.setText(Usuario.getNome());
        NomeCliente.setBorder(null);
        NomeCliente.setFocusable(false);
        NomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeClienteActionPerformed(evt);
            }
        });

        BotaoParcerias.setBackground(new java.awt.Color(204, 0, 0));
        BotaoParcerias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoParcerias.setForeground(new java.awt.Color(255, 255, 255));
        BotaoParcerias.setText("Parcerias");
        BotaoParcerias.setBorderPainted(false);
        BotaoParcerias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoParceriasActionPerformed(evt);
            }
        });

        BotaoRecarregarCelular.setBackground(new java.awt.Color(255, 102, 0));
        BotaoRecarregarCelular.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoRecarregarCelular.setForeground(new java.awt.Color(255, 255, 255));
        BotaoRecarregarCelular.setText("RecarregarCelular");
        BotaoRecarregarCelular.setBorderPainted(false);
        BotaoRecarregarCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRecarregarCelularActionPerformed(evt);
            }
        });

        BotaoPagar.setBackground(new java.awt.Color(255, 102, 0));
        BotaoPagar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoPagar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoPagar.setText("Pagamento e Depósito");
        BotaoPagar.setBorderPainted(false);
        BotaoPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPagarActionPerformed(evt);
            }
        });

        BotaoAreaPIX.setBackground(new java.awt.Color(255, 102, 0));
        BotaoAreaPIX.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoAreaPIX.setForeground(new java.awt.Color(255, 255, 255));
        BotaoAreaPIX.setText("Area Pix");
        BotaoAreaPIX.setToolTipText("");
        BotaoAreaPIX.setBorderPainted(false);
        BotaoAreaPIX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAreaPIXActionPerformed(evt);
            }
        });

        BotaoConsultarSaldo.setBackground(new java.awt.Color(204, 0, 0));
        BotaoConsultarSaldo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoConsultarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        BotaoConsultarSaldo.setText("R$ 𖧼𖧼𖧼𖧼️");
        BotaoConsultarSaldo.setBorderPainted(false);
        BotaoConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultarSaldoActionPerformed(evt);
            }
        });

        PerguntasFrequentes.setEditable(false);
        PerguntasFrequentes.setBackground(new java.awt.Color(255, 255, 255));
        PerguntasFrequentes.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        PerguntasFrequentes.setText("Perguntas Frequentes");
        PerguntasFrequentes.setBorder(null);
        PerguntasFrequentes.setFocusable(false);
        PerguntasFrequentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerguntasFrequentesActionPerformed(evt);
            }
        });

        BotaoPerfilConfiguracoes.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        BotaoPerfilConfiguracoes.setText("PERFIL E CONFIGURAÇÕES");
        BotaoPerfilConfiguracoes.setBorderPainted(false);
        BotaoPerfilConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPerfilConfiguracoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelHOMELayout = new javax.swing.GroupLayout(JPanelHOME);
        JPanelHOME.setLayout(JPanelHOMELayout);
        JPanelHOMELayout.setHorizontalGroup(
            JPanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelHOMELayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(JPanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanelHOMELayout.createSequentialGroup()
                        .addComponent(BotaoAreaPIX)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(BotaoRecarregarCelular))
                    .addGroup(JPanelHOMELayout.createSequentialGroup()
                        .addComponent(BotaoConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(JPanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelHOMELayout.createSequentialGroup()
                                .addComponent(BotaoConsultarExtrato)
                                .addGap(39, 39, 39)
                                .addComponent(BotaoParcerias, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelHOMELayout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(PerguntasFrequentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52))
            .addGroup(JPanelHOMELayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(JPanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoPerfilConfiguracoes)
                    .addGroup(JPanelHOMELayout.createSequentialGroup()
                        .addComponent(IconeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelHOMELayout.setVerticalGroup(
            JPanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelHOMELayout.createSequentialGroup()
                .addGroup(JPanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelHOMELayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(JPanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IconeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanelHOMELayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(PerguntasFrequentes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoPerfilConfiguracoes)
                .addGap(34, 34, 34)
                .addGroup(JPanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoConsultarExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoParcerias, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(JPanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoRecarregarCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoAreaPIX, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(JPanelHOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelHOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoConsultarExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultarExtratoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PaginaConsultarExtrato p1 = new PaginaConsultarExtrato();
        p1.setVisible(true);
    }//GEN-LAST:event_BotaoConsultarExtratoActionPerformed

    private void NomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeClienteActionPerformed

    private void BotaoParceriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoParceriasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PaginaParceiros p1 = new PaginaParceiros();
        p1.setVisible(true);
    }//GEN-LAST:event_BotaoParceriasActionPerformed

    private void BotaoRecarregarCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRecarregarCelularActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PaginaRecarregarCelular p1 = new PaginaRecarregarCelular();
        p1.setVisible(true);
    }//GEN-LAST:event_BotaoRecarregarCelularActionPerformed

    private void BotaoPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPagarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PaginaPagar p1 = new PaginaPagar();
        p1.setVisible(true);
    }//GEN-LAST:event_BotaoPagarActionPerformed

    private void BotaoAreaPIXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAreaPIXActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PaginaAreaPix p1 = new PaginaAreaPix();
        p1.setVisible(true);
    }//GEN-LAST:event_BotaoAreaPIXActionPerformed

    private void BotaoConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultarSaldoActionPerformed
        // TODO add your handling code here:
        try {
            ValidarInformacoesUsuario v1 = new ValidarInformacoesUsuario();
            v1.consultarSaldo();
            JOptionPane.showMessageDialog(null, "R$ "+Usuario.getSaldo(), "Saldo da conta", JOptionPane.INFORMATION_MESSAGE);
        } catch (ClassNotFoundException ex) {
            ex.getMessage();
        } catch (SQLException ex) {
            ex.getMessage();
        }

    }//GEN-LAST:event_BotaoConsultarSaldoActionPerformed

    private void PerguntasFrequentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerguntasFrequentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerguntasFrequentesActionPerformed

    private void BotaoPerfilConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPerfilConfiguracoesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PaginaPerfilConfiguracoes p1 = new PaginaPerfilConfiguracoes();
        p1.setVisible(true);
    }//GEN-LAST:event_BotaoPerfilConfiguracoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PaginaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAreaPIX;
    private javax.swing.JButton BotaoConsultarExtrato;
    private javax.swing.JButton BotaoConsultarSaldo;
    private javax.swing.JButton BotaoPagar;
    private javax.swing.JButton BotaoParcerias;
    private javax.swing.JButton BotaoPerfilConfiguracoes;
    private javax.swing.JButton BotaoRecarregarCelular;
    private javax.swing.JLabel IconeLogo;
    private javax.swing.JPanel JPanelHOME;
    private javax.swing.JTextField NomeCliente;
    private javax.swing.JTextField PerguntasFrequentes;
    // End of variables declaration//GEN-END:variables
}
